apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: log
spec:
  workspaces:
    - name: source
      description: shared workspace
    - name: maven-settings
      description: maven settings
    - name: maven-local-repo
      description: m2 things
  steps:
    - name: log
      image: alpine
      securityContext:
        runAsUser: 0
      script: |
        #!/bin/sh
        echo "ws path maven-settings: $(workspaces.maven-settings.path)"
        echo "ls of it:" 
        ls -lag $(workspaces.maven-settings.path)
        
        echo "ws path maven-workspace: $(workspaces.source.path)"
        echo "ls of it:" 
        ls -lag $(workspaces.source.path)
        
        echo "ws path maven-workspace target: $(workspaces.source.path)/target"
        echo "ls of it:" 
        ls -lag $(workspaces.source.path)/target
        
        echo "ws path maven-local-m2: $(workspaces.maven-local-repo.path)"
        echo "ls of it:" 
        ls -lag $(workspaces.maven-local-repo.path)
        
        echo "/workspace :"
        ls -lag /workspace