apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: clone-build-mvn-
spec:
  pipelineRef:
    name: clone-build-mvn
  podTemplate:
    securityContext:
      fsGroup: 65532
  workspaces:
    - name: maven-settings
      subPath: maven-repo-cache
      persistentVolumeClaim:
        claimName: source-pvc
    - name: source-workspace
      subPath: source
      persistentVolumeClaim:
        claimName: source-pvc
    - name: maven-local-m2
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
  params:
    - name: repo-url
      value: https://github.com/noldewit/bekant.git
    - name: image-reference
      value: 10.42.0.24:5000/bekant:0.0.1