apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: clone-build-mvn
spec:
  description: |
    This pipeline clones a git repo, builds using mvn and then more?
  workspaces:
    - name: source-workspace
    - name: maven-settings
    - name: maven-local-m2
  params:
    - name: repo-url
      type: string
    - name: image-reference
      type: string
  tasks:
    - name: fetch-source
      taskRef:
        name: git-clone
      workspaces:
        - name: output
          workspace: source-workspace
      params:
        - name: url
          value: $(params.repo-url)
        - name: subdirectory
          value: ""
        - name: deleteExisting
          value: "true"
    - name: log-it
      runAfter: [ "fetch-source" ]
      taskRef:
        name: log
      workspaces:
        - name: source
          workspace: source-workspace
        - name: maven-settings
          workspace: maven-settings
        - name: maven-local-repo
          workspace: maven-local-m2
    - name: build-mvn
      runAfter: [ "log-it" ]
      taskRef:
        name: maven
      workspaces:
        - name: source
          workspace: source-workspace
        - name: maven-settings
          workspace: maven-settings
        - name: maven-local-repo
          workspace: maven-local-m2
      params:
        - name: GOALS
          value:
            - -Dmaven.repo.local=$(workspaces.maven-settings.path)
            - -DskipTests
            - clean
            - compile
            - package
        - name: MAVEN_IMAGE
          value: gcr.io/cloud-builders/mvn:latest
    - name: log-it2
      taskRef:
        name: log
      runAfter: [ "build-mvn" ]
      workspaces:
        - name: source
          workspace: source-workspace
        - name: maven-settings
          workspace: maven-settings
        - name: maven-local-repo
          workspace: maven-local-m2
    - name: build-image
      runAfter: [ "log-it2" ]
      taskRef:
        name: kaniko
      workspaces:
        - name: source
          workspace: source-workspace
      params:
        - name: IMAGE
          value: 10.42.0.236:5000/bekant:bekant-image-01
    - name: log-it3
      taskRef:
        name: log
      runAfter: [ "build-image" ]
      workspaces:
        - name: source
          workspace: source-workspace
        - name: maven-settings
          workspace: maven-settings
        - name: maven-local-repo
          workspace: maven-local-m2

